using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DevExpress.Xpf.LayoutControl;
using DevExpress.Xpf.Editors;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DXLayoutControlSample {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {
        public MainWindow() {
            DataContext = new Contact {
                FirstName = "Carolyn",
                LastName = "Baker",
                Email = "carolyn.baker@example.com",
                Phone = "(555)349-3010",
                Address = "1198 Theresa Cir",
                City = "Whitinsville",
                State = "MA",
                Zip = "01582",
            };
            InitializeComponent();
        }
        private void OnDataLayoutControlAutoGeneratingItem(object sender, DataLayoutControlAutoGeneratingItemEventArgs e) {
            if (e.PropertyName == "Id")
                e.Cancel = true;
            if (e.PropertyName.ToLower().Contains("phone")) {
                var editor = new ButtonEdit() { Mask = "(000)000-0000", MaskType = MaskType.Simple };
                editor.SetBinding(BaseEdit.EditValueProperty, new Binding(e.PropertyName));
                e.Item.Content = editor;
            }
        }
        private void OnDataLayoutControlAutoGeneratedGroup(object sender, DataLayoutControlAutoGeneratedGroupEventArgs e) {
            e.Group.View = LayoutGroupView.Group;
        }
    }
    public class Contact {
        public int Id { get; set; }
        [Display(GroupName = "General")]
        public string FirstName { get; set; }
        [Display(GroupName = "General")]
        public string LastName { get; set; }
        [Display(GroupName = "Contacts")]
        public string Email { get; set; }
        [Display(GroupName = "Contacts")]
        public string Phone { get; set; }
        [Display(GroupName = "Address")]
        public string Address { get; set; }
        [Display(GroupName = "Address")]
        public string City { get; set; }
        [Display(GroupName = "Address")]
        public string State { get; set; }
        [Display(GroupName = "Address")]
        public string Zip { get; set; }
    }
}